### ISSUE TITLE
Session token not being refreshed?

### ISSUE THREAD

**Issue by JonRoma** [techservicesillinois/awscli-login#76] opened 2021-02-18 18:57 UTC
I've had a few instances where the session tokens appear to not be refreshed before they expire. The problem is solved by running `aws logout` followed by `aws login`, proving that my Shibboleth session is still active. Has anyone else seen this?

**Comment by ddriddle** [comment] 2021-02-18 19:26
@JonRoma can you post your log output from `~/.aws-login/log/*.log`?

**Comment by JonRoma** [comment] 2021-02-18 19:38
@ddriddle, I'll do this next time it happens so that I can conclusively determine that I'm giving you useful data by correlating it with the time on my wall clock. :)

While perusing the logs, I found two tidbits that may be worth noting:

First, the application is attempting to sleep for a *negative* time interval:

```
2021-02-17 21:27:07,524:INFO:Refresh failed: Authentication failed!
2021-02-17 21:27:07,524:INFO:Going to sleep for -158 seconds.
2021-02-17 21:27:07,525:ERROR:sleep length must be non-negative
```

Second, there is a typo (`startig` instead of `starting`):

```
2021-02-17 23:53:56,654:INFO:Startig refresh process for role arn:aws:iam::224588347132:role/ApplicationServicesAdmins
```

I can create separate issues for these if you would like.

**Comment by JonRoma** [comment] 2021-02-27 01:00
The awscli-login plugin again missed automatically refreshing my session token. This time, I can offer further details.

The first time I logged in Friday was late morning. The first log message attached (see below) is from 11:13:28. Though I feel as if I logged in earlier than that time, the log contains nothing indicating that I logged in, and the previous log entries date from Friday morning shortly after midnight, when my tokens from Thursday had reached their maximum lifetime.

Friday evening around 18:40, I checked to see whether my session was alive after a lapse of not doing anything with AWS for several hours, and found that it had expired. See terminal output below:

```
: aws s3 ls

An error occurred (ExpiredToken) when calling the ListBuckets operation: The provided token has expired.
: aws logout && aws login
Please choose the role you would like to assume:
     Account: 224588347132
         [ 0 ]: ApplicationServicesAdmins
     Account: 378517677616
         [ 1 ]: TechServicesStaff
     Account: 531841101767
         [ 2 ]: ApplicationServicesAdmins
     Account: 617683844790
         [ 3 ]: ApplicationServicesAdmins
     Account: 621331288878
         [ 4 ]: ApplicationServicesAdmins
     Account: 736533337653
         [ 5 ]: ADAdmins
Selection: 0
:
```

Here is the corresponding log from `~/.aws-login/log/default.log`:
```
2021-02-26 11:13:28,448:INFO:Startig refresh process for role arn:aws:iam::224588347132:role/ApplicationServicesAdmins
2021-02-26 11:13:28,449:INFO:Going to sleep for 3239 seconds.
2021-02-26 12:07:27,677:INFO:Loaded cookie jar: /Users/roma/.aws-login/cookies/roma.txt
2021-02-26 12:07:28,230:INFO:Successfully authenticated with cookies to endpoint: https://shibboleth.illinois.edu/idp/profile/SAML2/SOAP/ECP
2021-02-26 12:07:28,770:INFO:Retrieved temporary Amazon credentials for role: arn:aws:iam::224588347132:role/ApplicationServicesAdmins
2021-02-26 12:07:28,773:INFO:Saved temporary STS credentials to profile: default
2021-02-26 12:07:28,773:INFO:Going to sleep for 3239 seconds.
2021-02-26 13:01:27,920:INFO:Loaded cookie jar: /Users/roma/.aws-login/cookies/roma.txt
2021-02-26 13:01:28,515:INFO:Successfully authenticated with cookies to endpoint: https://shibboleth.illinois.edu/idp/profile/SAML2/SOAP/ECP
2021-02-26 13:01:28,992:INFO:Retrieved temporary Amazon credentials for role: arn:aws:iam::224588347132:role/ApplicationServicesAdmins
2021-02-26 13:01:28,996:INFO:Saved temporary STS credentials to profile: default
2021-02-26 13:01:28,996:INFO:Going to sleep for 3240 seconds.
2021-02-26 13:55:29,126:INFO:Loaded cookie jar: /Users/roma/.aws-login/cookies/roma.txt
2021-02-26 13:55:29,713:INFO:Successfully authenticated with cookies to endpoint: https://shibboleth.illinois.edu/idp/profile/SAML2/SOAP/ECP
2021-02-26 13:55:30,597:INFO:Retrieved temporary Amazon credentials for role: arn:aws:iam::224588347132:role/ApplicationServicesAdmins
2021-02-26 13:55:30,598:INFO:Saved temporary STS credentials to profile: default
2021-02-26 13:55:30,599:INFO:Going to sleep for 3239 seconds.
2021-02-26 15:24:03,272:INFO:Loaded cookie jar: /Users/roma/.aws-login/cookies/roma.txt
2021-02-26 15:24:04,244:INFO:Successfully authenticated with cookies to endpoint: https://shibboleth.illinois.edu/idp/profile/SAML2/SOAP/ECP
2021-02-26 15:24:04,749:INFO:Retrieved temporary Amazon credentials for role: arn:aws:iam::224588347132:role/ApplicationServicesAdmins
2021-02-26 15:24:04,752:INFO:Saved temporary STS credentials to profile: default
2021-02-26 15:24:04,752:INFO:Going to sleep for 3239 seconds.
2021-02-26 18:40:25,714:INFO:Received signal: SIGTERM. Shutting down...
2021-02-26 18:40:29,457:INFO:Startig refresh process for role arn:aws:iam::224588347132:role/ApplicationServicesAdmins
2021-02-26 18:40:29,458:INFO:Going to sleep for 3239 seconds.
```

You will notice that the session refreshing works happily for a while. However, at 15:24:04, the plugin indicated it was going to sleep (for approximately 54 minutes). It subsequently failed to wake up successfully, meaning the session terminated. The messages at 18:40:29 correspond with the `aws logout && aws login` I ran to manually refresh my session (which was successful). 

Something is affecting the background process from reawakening, and unfortunately it doesn't appear to leave any diagnostic information indicating why. If it is any help to you, I was away from the computer, and it went to sleep some time after 15:24:04.

**Comment by edthedev** [comment] 2021-03-02 22:02
That is helpful. Thanks!

Is this something we just have to live with, then? 

I don't think we want AWS CLI Login to keep the computer from sleeping.

**Comment by JonRoma** [comment] 2021-03-02 22:21
@edthedev, this seems to me to be new behavior, and is a somewhat different scenario than the one @ddriddle and I were troubleshooting in Spring 2019 before he went to Italy for the summer.

I feel as if there are several scenarios going on. To be blunt, I don't fully understand what goes on at an operating system level for either of

* A computer goes to sleep due to idleness.
* A laptop's cover is closed.

My gut tells me that these are different scenarios, and that they are likely somewhat different between macOS, Linux, and Windows.

David's initial design was to have a background daemon process that slept for roughly 90% of an hour time, in order that it refresh the token just before it is to expire when it hits one hour old. Back in 2019, I was able to find some evidence that the daemon process got confused if the computer woke up; it then apparently threw up its hands and barfed silently.

My hunch was that it couldn't handle the system timestamp changing out from under it, but we never really got to dig into this issue.

When the daemon process fails in this way, the simple logout/login fixes the situation. If the plugin is able to survive the computer going to sleep or having its cover closed, and detect wake-up (via a POSIX signal?) it would theoretically be able to replicate this behavior. The plugin is not preventing the computer from sleeping, but since computers sleeping are normal behavior, it ideally shouldn't have to be "goosed" after wake-up since magically handling token renewal is one of the key wins for this plugin.

**Comment by edthedev** [comment] 2021-03-02 22:30
@JonRoma  So what I think I'm hearing is:

The machine going to sleep is (likely) causing the background process to die (or get hopelessly stuck), so when the machine wakes, it doesn't try to refresh the token again until the next login causes the background process to restart?

If that sounds right, could you update the top-level description of this issue?

**Comment by edthedev** [comment] 2021-03-02 22:31
Actually, if that sounds right, then this is the same issue as #12.

**Comment by JonRoma** [comment] 2021-03-03 02:38
@edthedev, it may indeed be the same issue, but I defer to @ddriddle to merge the issues if he agrees. He and I haven't looked over the code together or spoken about this issue other than superficially for a _long_ time, probably not since the collapse of the Roman Empire. ;-) 

The first thing I would suggest is that there probably isn't sufficient logging detail to see what's happening, and there does not now seem to be a traceback produced by the daemon crashing (if indeed that's what's happened).

Does the plugin have debug-level log messages, and can a user activate that from the plugin's configuration file or command-line? I'm happy to play guinea pig, but there is not enough information now available to trace what's going on.

**Comment by edthedev** [comment] 2021-07-07 14:25
I am closing this for now as a likely duplicate of #12, but also have opened #88 so that we won't be guessing next time we look into this.

**Closed by edthedev** 2021-07-07 14:25 UTC
Labels: bug

**Comment by JonRoma** [comment] 2021-07-08 02:07
Maybe this should be moved to open ticket #12, but I *think* I have had my AWS session fail to renew. I'm pretty certain this was when I had not interacted with AWS for a while, but was doing other work that precluded my desktop iMac going to sleep.

One possible diagnostic tool would be to figure out where the various supported OSes log systems going to sleep, hibernating, etc. If this recurs, this could ascertain or refute my recollection about the machine not going to sleep.
