### ISSUE TITLE
Raspbian issues

### ISSUE THREAD

**Issue by AndreCouture** [techservicesillinois/awscli-login#40] opened 2020-04-23 20:35 UTC
On Raspbian Buster I was required to install libxslt1.1

then I get the following;

`
$ aws login
Password:
Factor:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/awscli_login/__main__.py", line 175, in main
    profile.cookies,
  File "/usr/local/lib/python3.7/dist-packages/awscli_login/saml.py", line 144, in refresh
    jar.load(ignore_discard=True)
  File "/usr/lib/python3.7/http/cookiejar.py", line 1794, in load
    self._really_load(f, filename, ignore_discard, ignore_expires)
  File "/usr/lib/python3.7/http/cookiejar.py", line 1897, in _really_load
    raise LoadError(msg)
http.cookiejar.LoadError: '/home/iot-user/.aws-login/cookies/myuser.txt' does not look like a Set-Cookie3 (LWP) format file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/awscli_login/__main__.py", line 123, in wrapper
    f(profile, session)
  File "/usr/local/lib/python3.7/dist-packages/awscli_login/__main__.py", line 180, in main
    profile.cookies, *creds)
  File "/usr/local/lib/python3.7/dist-packages/awscli_login/saml.py", line 118, in authenticate
    soap = saml_login(url, jar, username, password, headers)
  File "/usr/local/lib/python3.7/dist-packages/awscli_login/saml.py", line 92, in saml_login
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://d-xxxxxxxx.awsapps.com/start
403 Client Error: Forbidden for url: https://d-xxxxxxxx.awsapps.com/start
`

**Comment by ddriddle** [comment] 2020-04-27 21:42
Did you try removing the cookie file? That might fix your problem.

**Comment by edthedev** [comment] 2021-07-07 14:28
Closing this as assumed solved.

@AndreCouture please do re-open if the issue is still occurring.

**Closed by edthedev** 2021-07-07 14:28 UTC
